import AppKit
import ApplicationServices
import Carbon
import Foundation

// MARK: - AX helpers

func axCopy(_ element: AXUIElement, _ attribute: String) -> (AXError, CFTypeRef?) {
	var value: CFTypeRef?
	let err = AXUIElementCopyAttributeValue(element, attribute as CFString, &value)
	return (err, value)
}

func axString(_ element: AXUIElement, _ attribute: String) -> String? {
	axCopy(element, attribute).1 as? String
}

func axErrorName(_ e: AXError) -> String {
	switch e {
	case .success: "success"
	case .apiDisabled: "apiDisabled (no Accessibility permission)"
	case .noValue: "noValue"
	case .attributeUnsupported: "attributeUnsupported"
	case .cannotComplete: "cannotComplete"
	case .notImplemented: "notImplemented"
	case .illegalArgument: "illegalArgument"
	case .invalidUIElement: "invalidUIElement"
	default: "AXError(\(e.rawValue))"
	}
}

struct FocusedField {
	let element: AXUIElement
	let pid: pid_t
	let role: String
	let subrole: String
	var isSecure: Bool { subrole == kAXSecureTextFieldSubrole as String }
}

func focusedField() -> (FocusedField?, AXError) {
	let system = AXUIElementCreateSystemWide()
	// Messaging timeout keeps a hung target app from blocking us (default is ~6 s).
	AXUIElementSetMessagingTimeout(system, 0.25)
	let (err, value) = axCopy(system, kAXFocusedUIElementAttribute as String)
	guard err == .success, let value, CFGetTypeID(value) == AXUIElementGetTypeID() else { return (nil, err) }
	let element = value as! AXUIElement
	var pid: pid_t = 0
	AXUIElementGetPid(element, &pid)
	return (FocusedField(
		element: element,
		pid: pid,
		role: axString(element, kAXRoleAttribute as String) ?? "",
		subrole: axString(element, kAXSubroleAttribute as String) ?? ""
	), .success)
}

// MARK: - Pasteboard save / restore

struct SavedPasteboard {
	let items: [[(NSPasteboard.PasteboardType, Data)]]
	var typeCount: Int { items.reduce(0) { $0 + $1.count } }
	var byteCount: Int { items.reduce(0) { $0 + $1.reduce(0) { $0 + $1.1.count } } }

	/// Reads every type of every item. Forces promised/lazy data from the source app, which is
	/// the expensive part for big images or file promises.
	static func save(_ pb: NSPasteboard = .general) -> SavedPasteboard {
		SavedPasteboard(items: (pb.pasteboardItems ?? []).map { item in
			item.types.compactMap { type in item.data(forType: type).map { (type, $0) } }
		})
	}

	func restore(_ pb: NSPasteboard = .general) {
		pb.clearContents()
		guard !items.isEmpty else { return }
		pb.writeObjects(items.map { entries in
			let item = NSPasteboardItem()
			for (type, data) in entries { item.setData(data, forType: type) }
			return item
		})
	}

	func equals(_ other: SavedPasteboard) -> Bool {
		guard items.count == other.items.count else { return false }
		for (a, b) in zip(items, other.items) {
			let da = Dictionary(a, uniquingKeysWith: { x, _ in x })
			let db = Dictionary(b, uniquingKeysWith: { x, _ in x })
			if da != db { return false }
		}
		return true
	}
}

/// Serves our text lazily so we learn exactly when someone (the target app, or a clipboard
/// manager) reads it. That moment is the earliest safe point to restore the old clipboard.
final class PasteProvider: NSObject, NSPasteboardItemDataProvider {
	let text: String
	var requests: [(UInt64, String)] = []
	init(text: String) { self.text = text }

	func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
		requests.append((nowNs(), type.rawValue))
		item.setString(text, forType: type)
	}
}

let transientTypes: [NSPasteboard.PasteboardType] = [
	// nspasteboard.org conventions: clipboard managers skip these.
	.init("org.nspasteboard.TransientType"),
	.init("org.nspasteboard.ConcealedType"),
	.init("org.nspasteboard.AutoGeneratedType"),
]

func postCommandV() {
	let src = CGEventSource(stateID: .combinedSessionState)
	// kVK_ANSI_V is a physical position; on Dvorak-QWERTY⌘ layouts this still means ⌘V, on plain
	// Dvorak it would be ⌘K. yap should map "v" via UCKeyTranslate for the current layout.
	let v = CGKeyCode(kVK_ANSI_V)
	let down = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: true)
	down?.flags = .maskCommand
	let up = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: false)
	up?.flags = .maskCommand
	down?.post(tap: .cghidEventTap)
	up?.post(tap: .cghidEventTap)
}

// MARK: - Command

@MainActor
func runInsert(_ args: Args) {
	print("== Insertion")
	print("  Accessibility: \(AXIsProcessTrusted()), post events: \(CGPreflightPostEventAccess()), secure input: \(IsSecureEventInputEnabled())")
	print("  pasteboard accessBehavior: \(pasteboardAccessName(NSPasteboard.general.accessBehavior))")

	if args.flag("secure-demo") { runSecureDemo(); return }
	if args.flag("pasteboard-only") { runPasteboardOnly(args); return }
	if args.flag("focused") { runInsertFocused(args); return }

	guard AXIsProcessTrusted() else {
		print("  RESULT: blocked, Accessibility not granted (AX focused element returns apiDisabled; ⌘V posting is dropped)")
		let (_, err) = focusedField()
		print("  focused element query: \(axErrorName(err))")
		runPasteboardOnly(args)
		return
	}

	let previousApp = NSWorkspace.shared.frontmostApplication
	let textEditWasRunning = !NSRunningApplication.runningApplications(withBundleIdentifier: "com.apple.TextEdit").isEmpty
	let file = localDir.appendingPathComponent("insert-test.txt")
	try? "yap insert test\n".write(to: file, atomically: true, encoding: .utf8)
	// -g: open in the background so we do not steal focus for the AX part.
	_ = Children.shared.launch("/usr/bin/open", ["-g", "-a", "TextEdit", file.path])
	var field: FocusedField?
	runLoop(for: 8) {
		field = textEditField()
		return field?.role == kAXTextAreaRole as String
	}
	guard let field, field.role == kAXTextAreaRole as String else {
		print("  RESULT: could not find TextEdit's focused text area via AX; aborting (nothing posted)")
		return
	}
	print("  TextEdit field (app-level focus, app in background): pid \(field.pid) role \(field.role) subrole '\(field.subrole)' secure=\(field.isSecure)")
	let runs = args.int("runs", 5)

	// (a) AX: set kAXSelectedTextAttribute.
	var axTimes: [Double] = []
	var axVerified = 0
	for i in 0..<runs {
		let marker = " [ax\(i)]"
		let t0 = nowNs()
		let err = AXUIElementSetAttributeValue(field.element, kAXSelectedTextAttribute as CFString, marker as CFString)
		let t1 = nowNs()
		axTimes.append(msValue(t1 - t0))
		// Some apps (Electron, some web views) return success but ignore the write: verify.
		if err == .success, axString(field.element, kAXValueAttribute as String)?.contains(marker) == true { axVerified += 1 }
		if err != .success { print("    ax set error: \(axErrorName(err))") }
	}
	print("  (a) AX set selected text: \(stats(axTimes)); verified \(axVerified)/\(runs)")

	// (b) Paste fallback with save/restore and a lazy provider.
	let userClipboard = SavedPasteboard.save()
	defer { userClipboard.restore() }
	// Put a known multi-type clipboard in place so we can check restore fidelity.
	let pb = NSPasteboard.general
	pb.clearContents()
	let rich = NSPasteboardItem()
	rich.setString("before-text", forType: .string)
	rich.setData(Data("{\\rtf1 before}".utf8), forType: .rtf)
	rich.setData(Data([1, 2, 3, 4]), forType: .init("com.bjornbom.yap.custom"))
	pb.writeObjects([rich])

	var saveTimes: [Double] = [], setTimes: [Double] = [], provideTimes: [Double] = [], appearTimes: [Double] = []
	var restoreOK = 0
	NSRunningApplication(processIdentifier: field.pid)?.activate()
	let front = runLoop(for: 3) { focusedField().0?.pid == field.pid }
	print("  (b) activated TextEdit for ⌘V: system-wide focus on TextEdit = \(front)")
	for i in 0..<runs {
		// ⌘V goes to whatever is focused, so check right before every post.
		guard NSWorkspace.shared.frontmostApplication?.bundleIdentifier == "com.apple.TextEdit",
			focusedField().0?.pid == field.pid
		else {
			print("    TextEdit not focused (frontmost: \(NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "nil")); skipping paste trial \(i)")
			continue
		}
		let marker = " [paste\(i)]"
		let t0 = nowNs()
		let saved = SavedPasteboard.save()
		let t1 = nowNs()
		let provider = PasteProvider(text: marker)
		pb.clearContents()
		let item = NSPasteboardItem()
		item.setDataProvider(provider, forTypes: [.string])
		for t in transientTypes { item.setString("", forType: t) }
		pb.writeObjects([item])
		let t2 = nowNs()
		postCommandV()
		let posted = nowNs()
		// Do not make synchronous AX calls into the target while it may be blocked asking us for
		// the lazy pasteboard data: both sides wait until the AX messaging timeout (0.25 s here).
		if !args.flag("naive-wait") { runLoop(for: 2) { !provider.requests.isEmpty } }
		let appeared = runLoop(for: 2) { axString(field.element, kAXValueAttribute as String)?.contains(marker) == true }
		let t3 = nowNs()
		if let first = provider.requests.first { provideTimes.append(msValue(first.0 - posted)) }
		if appeared { appearTimes.append(msValue(t3 - posted)) }
		saved.restore()
		if SavedPasteboard.save().equals(saved) { restoreOK += 1 }
		saveTimes.append(msValue(t1 - t0))
		setTimes.append(msValue(t2 - t1))
		print("    run \(i): provider requests \(provider.requests.map { "\($0.1) +\(String(format: "%.1f", msValue($0.0 - posted))) ms" }), text appeared: \(appeared)")
		runLoop(for: 0.2)
	}
	print("  (b) save pasteboard (\(SavedPasteboard.save().typeCount) types): \(stats(saveTimes))")
	print("      set pasteboard: \(stats(setTimes))")
	print("      ⌘V posted -> target requested data: \(stats(provideTimes))")
	print("      ⌘V posted -> text visible via AX: \(stats(appearTimes))")
	print("      restore fidelity: \(restoreOK)/\(runs) identical")
	print("      user clipboard: \(userClipboard.items.count) items, \(userClipboard.typeCount) types, \(userClipboard.byteCount) bytes (restored on exit)")

	if !textEditWasRunning {
		NSRunningApplication.runningApplications(withBundleIdentifier: "com.apple.TextEdit").forEach { $0.terminate() }
	}
	previousApp?.activate()
}

/// TextEdit's focused element via its application element: works while TextEdit is in the
/// background, unlike the system-wide focused element.
func textEditField() -> FocusedField? {
	guard let app = NSRunningApplication.runningApplications(withBundleIdentifier: "com.apple.TextEdit").first else { return nil }
	let element = AXUIElementCreateApplication(app.processIdentifier)
	AXUIElementSetMessagingTimeout(element, 0.25)
	guard let value = axCopy(element, kAXFocusedUIElementAttribute as String).1, CFGetTypeID(value) == AXUIElementGetTypeID() else { return nil }
	let focused = value as! AXUIElement
	return FocusedField(
		element: focused,
		pid: app.processIdentifier,
		role: axString(focused, kAXRoleAttribute as String) ?? "",
		subrole: axString(focused, kAXSubroleAttribute as String) ?? ""
	)
}

/// Manual tool: after a delay, insert into whatever field the user focused, AX first and
/// ⌘V as fallback, the way yap's Inserter would. Used for MANUAL.md step 6.
@MainActor
func runInsertFocused(_ args: Args) {
	let delay = args.double("delay", 3)
	let text = args.value("text") ?? " [yap]"
	print("  focus a text field in the target app within \(Int(delay)) s ...")
	runLoop(for: delay)
	let (target, err) = focusedField()
	guard let target else { print("  no focused element: \(axErrorName(err))"); return }
	let app = NSRunningApplication(processIdentifier: target.pid)?.bundleIdentifier ?? "?"
	print("  target: \(app) pid \(target.pid) role \(target.role) subrole '\(target.subrole)'")
	if target.isSecure || IsSecureEventInputEnabled() {
		print("  RESULT: secure field / secure input -> nothing inserted"); return
	}
	let before = axString(target.element, kAXValueAttribute as String)
	let t0 = nowNs()
	let axErr = AXUIElementSetAttributeValue(target.element, kAXSelectedTextAttribute as CFString, text as CFString)
	let axMs = msValue(nowNs() - t0)
	let after = axString(target.element, kAXValueAttribute as String)
	let verified = axErr == .success && after != before && after?.contains(text) == true
	print("  AX set: \(axErrorName(axErr)) in \(String(format: "%.1f", axMs)) ms; value readable: \(after != nil); verified: \(verified)")
	if verified { print("  RESULT: inserted via AX"); return }
	guard focusedField().0?.pid == target.pid else { print("  RESULT: focus changed, nothing pasted"); return }
	let saved = SavedPasteboard.save()
	let provider = PasteProvider(text: text)
	NSPasteboard.general.clearContents()
	let item = NSPasteboardItem()
	item.setDataProvider(provider, forTypes: [.string])
	for t in transientTypes { item.setString("", forType: t) }
	NSPasteboard.general.writeObjects([item])
	let posted = nowNs()
	postCommandV()
	let requested = runLoop(for: 0.5) { !provider.requests.isEmpty }
	runLoop(for: 0.05)
	saved.restore()
	let when = provider.requests.first.map { String(format: "%.1f ms", msValue($0.0 - posted)) } ?? "never"
	print("  RESULT: \(requested ? "pasted via ⌘V" : "⌘V ignored (no data request)"); data requested after \(when); clipboard restored")
}

/// Pasteboard save/set/restore timings that need no permission.
@MainActor
func runPasteboardOnly(_ args: Args) {
	let runs = args.int("runs", 20)
	let userClipboard = SavedPasteboard.save()
	defer { userClipboard.restore() }
	var save: [Double] = [], set: [Double] = [], restore: [Double] = []
	var ok = 0
	for i in 0..<runs {
		let t0 = nowNs()
		let saved = SavedPasteboard.save()
		let t1 = nowNs()
		NSPasteboard.general.clearContents()
		let item = NSPasteboardItem()
		item.setString("yap \(i)", forType: .string)
		for t in transientTypes { item.setString("", forType: t) }
		NSPasteboard.general.writeObjects([item])
		let t2 = nowNs()
		saved.restore()
		let t3 = nowNs()
		if SavedPasteboard.save().equals(saved) { ok += 1 }
		save.append(msValue(t1 - t0)); set.append(msValue(t2 - t1)); restore.append(msValue(t3 - t2))
	}
	print("  pasteboard only (user clipboard: \(userClipboard.items.count) items, \(userClipboard.typeCount) types, \(userClipboard.byteCount) bytes)")
	print("    save    \(stats(save))")
	print("    set     \(stats(set))")
	print("    restore \(stats(restore)); fidelity \(ok)/\(runs)")
}

/// Runs a system-wide AX focus query off the main thread. When the focused element belongs to
/// this process, a main-thread query would wait on itself until the AX messaging timeout.
@MainActor
func focusedFieldOffMain() -> (FocusedField?, AXError) {
	final class Box: @unchecked Sendable { var value: (FocusedField?, AXError)? }
	let box = Box()
	DispatchQueue.global().async { box.value = focusedField() }
	runLoop(for: 2) { box.value != nil }
	return box.value ?? (nil, .cannotComplete)
}

/// Probes off the happy path, all inside our own windows so nothing reaches other apps:
/// 1. a focused window with no text field, 2. a focused NSSecureTextField.
@MainActor
func runSecureDemo() {
	let app = NSApplication.shared
	// .accessory + activate() does not take focus from the frontmost app on macOS 26
	// (cooperative activation), so become a regular app and ask explicitly.
	app.setActivationPolicy(.regular)
	app.finishLaunching() // without it the process answers AX with notImplemented
	let previousApp = NSWorkspace.shared.frontmostApplication
	let userClipboard = SavedPasteboard.save()
	defer { userClipboard.restore(); previousApp?.activate() }

	func show(_ title: String, _ content: NSView) -> NSWindow {
		let window = NSWindow(contentRect: NSRect(x: 200, y: 200, width: 320, height: 80), styleMask: [.titled], backing: .buffered, defer: false)
		window.title = title
		window.contentView?.addSubview(content)
		window.makeKeyAndOrderFront(nil)
		app.activate(ignoringOtherApps: true)
		window.makeFirstResponder(content)
		runLoop(for: 1.0)
		return window
	}

	func tryInsert(_ label: String) {
		print("  [\(label)] app active: \(app.isActive), frontmost: \(NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "nil")")
		let (focused, err) = focusedFieldOffMain()
		guard let focused else { print("  [\(label)] AX focused element: \(axErrorName(err))"); return }
		print("  [\(label)] AX focused: pid \(focused.pid) (self \(getpid())) role \(focused.role) subrole '\(focused.subrole)' isSecure=\(focused.isSecure); IsSecureEventInputEnabled=\(IsSecureEventInputEnabled())")
		guard focused.pid == getpid() else {
			print("  [\(label)] focus is in another app; probe aborted, nothing inserted or posted")
			return
		}
		if focused.isSecure || IsSecureEventInputEnabled() {
			print("  [\(label)] policy: secure field -> insert nothing, keep text for 'paste last'")
			return
		}
		final class Box: @unchecked Sendable { var err: AXError? }
		let box = Box()
		let element = focused.element
		DispatchQueue.global().async {
			box.err = AXUIElementSetAttributeValue(element, kAXSelectedTextAttribute as CFString, "probe" as CFString)
		}
		runLoop(for: 2) { box.err != nil }
		print("  [\(label)] AX set selected text -> \(box.err.map(axErrorName) ?? "timeout")")
		// Paste fallback into a non-text target: does anyone ever ask for the data?
		let provider = PasteProvider(text: "probe")
		NSPasteboard.general.clearContents()
		let item = NSPasteboardItem()
		item.setDataProvider(provider, forTypes: [.string])
		NSPasteboard.general.writeObjects([item])
		postCommandV()
		runLoop(for: 1.0) { !provider.requests.isEmpty }
		print("  [\(label)] ⌘V -> pasteboard data requested: \(!provider.requests.isEmpty) (no request = nothing pasted; restore on timeout)")
	}

	let button = NSButton(title: "no text here", target: nil, action: nil)
	button.frame = NSRect(x: 20, y: 25, width: 280, height: 24)
	let plain = show("yapio probe: no text field", button)
	tryInsert("no text field")
	plain.close()

	let field = NSSecureTextField(frame: NSRect(x: 20, y: 25, width: 280, height: 24))
	let secure = show("yapio probe: secure field", field)
	tryInsert("secure field")
	secure.close()
	runLoop(for: 0.3)
	print("  after close, IsSecureEventInputEnabled: \(IsSecureEventInputEnabled())")
}
